---
# Construit la liste de paquets effectifs pour CETTE machine
- name: Preflight | Construire liste de paquets effectifs pour cette distro
  ansible.builtin.set_fact:
    pkgs_effective: >-
      {{ (packages_common_effective | default(packages.common))
         + (packages.by_distro[ansible_distribution] | default([]))
         + (packages.by_os_family[ansible_os_family] | default([])) }}

# Suggestions connues
- name: Preflight | Suggestions de remplacement par plateforme
  ansible.builtin.set_fact:
    pkg_suggestions:
      Archlinux:
        wireshark: "wireshark-qt ou wireshark-cli"
        dnsutils: "bind-tools"
        fd-find: "fd"
        python3-venv: "python-virtualenv"
        tldr: "tealdeer"
        python3: "python"
        clang-tidy: "fourni par 'clang' (pas de paquet séparé)"
        clang-format: "fourni par 'clang' (pas de paquet séparé)"
      Debian:
        fd: "fd-find"
        go: "golang-go"
      Ubuntu:
        fd: "fd-find"
        go: "golang-go"

# ... le reste du fichier inchangé ...
